/**
 * invoiceService.ts — Invoice management for the mobile app.
 *
 * Invoices are READ-ONLY on mobile (generated by backend).
 * This service handles fetching, PDF caching, and sending.
 */

import type { Database } from '@nozbe/watermelondb';
import { Q } from '@nozbe/watermelondb';
import type { AxiosInstance } from 'axios';
import { Directory, File, Paths } from 'expo-file-system';
import type Invoice from '@/db/models/Invoice';
import type Patient from '@/db/models/Patient';
import { encryptFile, decryptFileToBase64, deleteFileSecurely } from '@/security/encryption';
import { globalQueue } from '@/services/globalQueue';
import { formatPatientName } from '@/utils/formatters';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface InvoiceAct {
  code: string;
  label: string;
  amount: number;
  coefficient?: number;
  quantity?: number;
}

export interface InvoiceDetail {
  id: string;
  serverId: string;
  appointmentId: string;
  patientId: string;
  patientName: string;
  patientEmail: string | null;
  patientPhone: string | null;
  invoiceNumber: string;
  date: string;
  status: 'draft' | 'validated' | 'cancelled';
  vitaleStatus: 'not_read' | 'read_pending' | 'validated';
  acts: InvoiceAct[];
  totalAmount: number;
  amountAmo: number;
  amountAmc: number;
  amountPatient: number;
  pdfLocalPath: string | null;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function buildInvoiceDetail(invoice: Invoice, patient: Patient): InvoiceDetail {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const raw = (invoice as any)._raw;
  return {
    id: invoice.id,
    serverId: raw.server_id ?? '',
    appointmentId: raw.appointment_id ?? '',
    patientId: raw.patient_id ?? '',
    patientName: formatPatientName(patient.firstName, patient.lastName),
    patientEmail: patient.email ?? null,
    patientPhone: patient.phone ?? null,
    invoiceNumber: raw.invoice_number ?? '',
    date: raw.created_at
      ? new Date(raw.created_at).toISOString().split('T')[0]
      : '',
    status: raw.status as InvoiceDetail['status'],
    vitaleStatus: (raw.vitale_status ?? 'not_read') as InvoiceDetail['vitaleStatus'],
    acts: [],
    totalAmount: raw.total_amount ?? 0,
    amountAmo: raw.amount_amo ?? 0,
    amountAmc: raw.amount_amc ?? 0,
    amountPatient: raw.amount_patient ?? 0,
    pdfLocalPath: raw.pdf_local_path ?? null,
  };
}

function parseServerInvoice(
  data: Record<string, unknown>,
  patient: Patient,
  localId: string,
): InvoiceDetail {
  const acts: InvoiceAct[] = Array.isArray(data.items)
    ? (data.items as Record<string, unknown>[]).map((item) => ({
        code: String(item.act_code ?? ''),
        label: String(item.label ?? item.description ?? ''),
        amount: Number(item.amount ?? 0),
        coefficient: item.coefficient != null ? Number(item.coefficient) : undefined,
        quantity: item.quantity != null ? Number(item.quantity) : undefined,
      }))
    : [];

  return {
    id: localId,
    serverId: String(data.id ?? ''),
    appointmentId: String(data.appointment_id ?? ''),
    patientId: String(data.patient_id ?? ''),
    patientName: formatPatientName(patient.firstName, patient.lastName),
    patientEmail: patient.email ?? null,
    patientPhone: patient.phone ?? null,
    invoiceNumber: String(data.invoice_number ?? ''),
    date: String(data.created_at ?? '').split('T')[0],
    status: (data.status as InvoiceDetail['status']) ?? 'draft',
    vitaleStatus: (data.vitale_status as InvoiceDetail['vitaleStatus']) ?? 'not_read',
    acts,
    totalAmount: Number(data.total_ttc ?? data.total_amount ?? 0),
    amountAmo: Number(data.amount_amo ?? 0),
    amountAmc: Number(data.amount_amc ?? 0),
    amountPatient: Number(data.amount_patient ?? 0),
    pdfLocalPath: null,
  };
}

// ---------------------------------------------------------------------------
// Fetch
// ---------------------------------------------------------------------------

/**
 * Get the invoice associated with an appointment.
 * Looks in local DB first, then tries server if online.
 */
export async function getInvoiceForAppointment(
  database: Database,
  apiClient: AxiosInstance | null,
  appointmentId: string,
): Promise<InvoiceDetail | null> {
  // 1. Try local DB
  const localInvoices = await database
    .get<Invoice>('invoices')
    .query(Q.where('appointment_id', appointmentId))
    .fetch();

  if (localInvoices.length > 0) {
    const invoice = localInvoices[0];
    try {
      const patient = await database.get<Patient>('patients').find(invoice.patientId);
      return buildInvoiceDetail(invoice, patient);
    } catch {
      return buildInvoiceDetail(invoice, { firstName: '', lastName: 'Inconnu' } as Patient);
    }
  }

  // 2. Try server
  if (!apiClient) return null;

  try {
    // We need the server-side appointment ID — look it up
    const { default: Appointment } = await import('@/db/models/Appointment');
    void Appointment; // ensure import is used
    const appt = await database.get('appointments').find(appointmentId);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const serverId = (appt as any)._raw.server_id;
    if (!serverId) return null;

    const response = await apiClient.get(`/appointments/${serverId}/invoice`);
    const data = response.data as Record<string, unknown>;

    // Resolve patient
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const patientLocalId = (appt as any)._raw.patient_id as string;
    let patient: Patient;
    try {
      patient = await database.get<Patient>('patients').find(patientLocalId);
    } catch {
      patient = { firstName: '', lastName: 'Inconnu' } as Patient;
    }

    // Save to local DB
    let localRecordId = '';
    await database.write(async () => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const record = await database.get('invoices').create((rec: any) => {
        rec._raw.server_id = String(data.id ?? '');
        rec._raw.appointment_id = appointmentId;
        rec._raw.patient_id = patientLocalId;
        rec._raw.invoice_number = String(data.invoice_number ?? '');
        rec._raw.total_amount = Number(data.total_ttc ?? data.total_amount ?? 0);
        rec._raw.amount_amo = Number(data.amount_amo ?? 0);
        rec._raw.amount_amc = Number(data.amount_amc ?? 0);
        rec._raw.amount_patient = Number(data.amount_patient ?? 0);
        rec._raw.status = String(data.status ?? 'draft');
        rec._raw.pdf_local_path = null;
        rec._raw.vitale_status = String(data.vitale_status ?? 'not_read');
        rec._raw.created_at = Date.now();
        rec._raw.last_synced_at = Date.now();
      });
      localRecordId = (record as { id: string }).id;
    });

    return parseServerInvoice(data, patient, localRecordId);
  } catch {
    return null;
  }
}

/**
 * Get an invoice by its local WatermelonDB ID.
 */
export async function getInvoiceById(
  database: Database,
  apiClient: AxiosInstance | null,
  invoiceId: string,
): Promise<InvoiceDetail | null> {
  try {
    const invoice = await database.get<Invoice>('invoices').find(invoiceId);
    const patient = await database.get<Patient>('patients').find(invoice.patientId);
    const detail = buildInvoiceDetail(invoice, patient);

    // If we have a server ID and online, try to enrich with acts
    if (detail.serverId && apiClient && detail.acts.length === 0) {
      try {
        const response = await apiClient.get(`/invoices/${detail.serverId}`);
        const data = response.data as Record<string, unknown>;
        if (Array.isArray(data.items)) {
          detail.acts = (data.items as Record<string, unknown>[]).map((item) => ({
            code: String(item.act_code ?? ''),
            label: String(item.label ?? item.description ?? ''),
            amount: Number(item.amount ?? 0),
            coefficient: item.coefficient != null ? Number(item.coefficient) : undefined,
            quantity: item.quantity != null ? Number(item.quantity) : undefined,
          }));
        }
      } catch {
        // Acts enrichment failure is non-critical
      }
    }

    return detail;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// PDF
// ---------------------------------------------------------------------------

const INVOICES_DIR_NAME = 'invoices';

async function ensureInvoicesDir(): Promise<void> {
  const dir = new Directory(Paths.document, INVOICES_DIR_NAME);
  if (!dir.exists) {
    dir.create();
  }
}

/**
 * Download the invoice PDF from the server, encrypt it, and cache locally.
 * Returns the encrypted file path.
 */
export async function downloadAndCachePdf(
  database: Database,
  apiClient: AxiosInstance,
  invoiceId: string,
  serverId: string,
): Promise<string> {
  await ensureInvoicesDir();

  const uuid = `${Date.now()}_${Math.random().toString(36).substring(2, 8)}`;
  const tempFile = new File(Paths.cache, `invoice_temp_${uuid}.pdf`);
  const destFile = new File(
    new Directory(Paths.document, INVOICES_DIR_NAME),
    `invoice_${uuid}.pdf.enc`,
  );

  try {
    // Download PDF from server
    const response = await apiClient.get(`/invoices/${serverId}/pdf`, {
      responseType: 'arraybuffer',
    });

    // Write to temp file
    const bytes = new Uint8Array(response.data as ArrayBuffer);
    let binary = '';
    for (let i = 0; i < bytes.length; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    tempFile.write(btoa(binary));

    // Encrypt and move
    await encryptFile(tempFile.uri, destFile.uri);

    // Clean temp
    await deleteFileSecurely(tempFile.uri);

    // Update local DB with cached path
    await database.write(async () => {
      const invoice = await database.get<Invoice>('invoices').find(invoiceId);
      await invoice.update(() => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (invoice as any)._raw.pdf_local_path = destFile.uri;
      });
    });

    return destFile.uri;
  } catch (err) {
    // Clean up on error
    try {
      await deleteFileSecurely(tempFile.uri);
    } catch {
      // ignore
    }
    throw err;
  }
}

/**
 * Returns the cached PDF path if the file exists on disk, null otherwise.
 */
export async function getCachedPdfPath(
  database: Database,
  invoiceId: string,
): Promise<string | null> {
  try {
    const invoice = await database.get<Invoice>('invoices').find(invoiceId);
    const path = invoice.pdfLocalPath;
    if (!path) return null;

    const file = new File(path);
    if (file.exists) return path;

    // Path set but file gone — clear it
    await database.write(async () => {
      await invoice.update(() => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (invoice as any)._raw.pdf_local_path = null;
      });
    });
    return null;
  } catch {
    return null;
  }
}

/**
 * Decrypt a cached PDF and return its base64 content.
 */
export async function decryptCachedPdf(encryptedPath: string): Promise<string> {
  return decryptFileToBase64(encryptedPath);
}

// ---------------------------------------------------------------------------
// Send
// ---------------------------------------------------------------------------

/**
 * Send an invoice to the patient via email or SMS.
 * If offline, enqueues the operation for later processing.
 */
export async function sendInvoice(
  apiClient: AxiosInstance | null,
  invoiceServerId: string,
  channel: 'email' | 'sms',
  recipient: string,
): Promise<void> {
  const body =
    channel === 'email'
      ? { channel, email: recipient }
      : { channel, phone: recipient };

  if (apiClient) {
    try {
      await apiClient.post(`/invoices/${invoiceServerId}/send`, body);
      return;
    } catch {
      // Network failure — enqueue
    }
  }

  await globalQueue.enqueue('POST', `/invoices/${invoiceServerId}/send`, body);
}

// ---------------------------------------------------------------------------
// Carte Vitale placeholder
// ---------------------------------------------------------------------------

/**
 * PLACEHOLDER — Carte Vitale validation.
 *
 * Future integration via e-CPS or NFC Bluetooth reader.
 * See: docs/roadmap-homologation-sesam-vitale.md, iteration 8.
 *
 * Will change vitale_status from 'not_read' → 'read_pending' → 'validated'.
 */
export async function validateVitaleCard(_invoiceId: string): Promise<void> {
  // Not implemented yet — placeholder for future iteration
}

// ---------------------------------------------------------------------------
// HTML fallback
// ---------------------------------------------------------------------------

/**
 * Generate an HTML invoice for local display when server PDF is unavailable.
 * Returns complete HTML string suitable for rendering in a WebView.
 */
export function generateInvoiceHtml(invoice: InvoiceDetail): string {
  const fmt = (n: number) => n.toFixed(2).replace('.', ',');

  const actRows = invoice.acts.length > 0
    ? invoice.acts
        .map(
          (a) =>
            `<tr><td class="code">${esc(a.code)}</td><td>${esc(a.label)}</td><td class="amt">${fmt(a.amount)} &euro;</td></tr>`,
        )
        .join('\n')
    : '<tr><td colspan="3" class="empty">Actes non detailles</td></tr>';

  const statusLabel =
    invoice.status === 'validated'
      ? 'Validee'
      : invoice.status === 'draft'
      ? 'Brouillon'
      : invoice.status;

  return `<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, system-ui, sans-serif; background: #F8FAFC; color: #1E293B; padding: 24px 16px; }
  .header { text-align: center; margin-bottom: 24px; }
  .header h1 { font-size: 20px; font-weight: 800; }
  .header .number { font-size: 14px; color: #64748B; margin-top: 4px; }
  .badge { display: inline-block; padding: 3px 10px; border-radius: 6px; font-size: 12px; font-weight: 700; background: ${invoice.status === 'validated' ? '#DCFCE7' : '#FFF7ED'}; color: ${invoice.status === 'validated' ? '#16A34A' : '#EA580C'}; }
  .info { background: #fff; border: 1px solid #E2E8F0; border-radius: 10px; padding: 14px; margin-bottom: 20px; }
  .info-row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #F1F5F9; }
  .info-row:last-child { border-bottom: none; }
  .info-row .label { color: #64748B; font-size: 13px; }
  .info-row .value { font-weight: 600; font-size: 14px; }
  table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #E2E8F0; border-radius: 10px; overflow: hidden; margin-bottom: 20px; }
  th { background: #F1F5F9; text-align: left; padding: 8px 12px; font-size: 11px; text-transform: uppercase; color: #64748B; letter-spacing: 0.5px; }
  td { padding: 10px 12px; border-top: 1px solid #F1F5F9; font-size: 13px; }
  .code { font-weight: 700; color: #2563EB; white-space: nowrap; }
  .amt { text-align: right; font-weight: 600; font-variant-numeric: tabular-nums; white-space: nowrap; }
  .empty { color: #94A3B8; font-style: italic; }
  .totals { background: #fff; border: 1px solid #E2E8F0; border-radius: 10px; overflow: hidden; }
  .total-row { display: flex; justify-content: space-between; padding: 10px 14px; border-bottom: 1px solid #F1F5F9; }
  .total-row:last-child { border-bottom: none; }
  .total-row.main { font-weight: 800; font-size: 15px; background: #F8FAFC; }
  .total-row .label { font-size: 13px; color: #64748B; }
  .total-row .value { font-size: 13px; font-weight: 600; font-variant-numeric: tabular-nums; }
  .zero { color: #16A34A; }
  .footer { text-align: center; margin-top: 32px; font-size: 11px; color: #94A3B8; }
</style>
</head>
<body>
  <div class="header">
    <h1>Facture</h1>
    <div class="number">N&deg; ${esc(invoice.invoiceNumber)}</div>
    <div style="margin-top:8px"><span class="badge">${esc(statusLabel)}</span></div>
  </div>

  <div class="info">
    <div class="info-row"><span class="label">Patient</span><span class="value">${esc(invoice.patientName)}</span></div>
    <div class="info-row"><span class="label">Date</span><span class="value">${esc(invoice.date)}</span></div>
    <div class="info-row"><span class="label">Montant total</span><span class="value" style="font-size:16px;font-weight:800">${fmt(invoice.totalAmount)} &euro;</span></div>
  </div>

  <table>
    <tr><th>Code</th><th>Acte</th><th style="text-align:right">Montant</th></tr>
    ${actRows}
  </table>

  <div class="totals">
    <div class="total-row main"><span>TOTAL</span><span>${fmt(invoice.totalAmount)} &euro;</span></div>
    <div class="total-row"><span class="label">Part AMO (Secu)</span><span class="value">${fmt(invoice.amountAmo)} &euro;</span></div>
    <div class="total-row"><span class="label">Part complementaire</span><span class="value">${fmt(invoice.amountAmc)} &euro;</span></div>
    <div class="total-row"><span class="label">Reste a charge patient</span><span class="value${invoice.amountPatient === 0 ? ' zero' : ''}">${fmt(invoice.amountPatient)} &euro;</span></div>
  </div>

  <div class="footer">Document genere localement &mdash; IDEL Assistant</div>
</body>
</html>`;
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
