// WatermelonDB schema v1 for IDEL Assistant offline-first database
// All tables mirror backend entities with server_id for sync tracking

import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'patients',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'first_name', type: 'string' },
        { name: 'last_name', type: 'string' },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'address', type: 'string' },
        { name: 'lat', type: 'number', isOptional: true },
        { name: 'lon', type: 'number', isOptional: true },
        { name: 'birth_date', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'is_ald', type: 'boolean' },
        { name: 'has_active_bsi', type: 'boolean' },
        { name: 'bsi_level', type: 'string', isOptional: true },
        { name: 'bsi_end_date', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'last_synced_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'appointments',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'string' },
        { name: 'date', type: 'string', isIndexed: true },
        { name: 'start_time', type: 'string' },
        { name: 'end_time', type: 'string' },
        { name: 'care_type_code', type: 'string' },
        { name: 'care_type_label', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'location_type', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'sort_order', type: 'number' },
        { name: 'completed_at', type: 'number', isOptional: true },
        { name: 'last_synced_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'transmissions',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'appointment_id', type: 'string', isOptional: true },
        { name: 'author_user_id', type: 'string' },
        { name: 'author_name', type: 'string' },
        { name: 'content_text', type: 'string', isOptional: true },
        { name: 'content_structured', type: 'string', isOptional: true },
        { name: 'audio_file_path', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'audio_uploaded', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'last_synced_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'invoices',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'appointment_id', type: 'string' },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'invoice_number', type: 'string' },
        { name: 'total_amount', type: 'number' },
        { name: 'amount_amo', type: 'number' },
        { name: 'amount_amc', type: 'number' },
        { name: 'amount_patient', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'pdf_local_path', type: 'string', isOptional: true },
        { name: 'vitale_status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'last_synced_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'documents',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'prescription_id', type: 'string', isOptional: true },
        { name: 'file_type', type: 'string' },
        { name: 'local_file_path', type: 'string' },
        { name: 'uploaded', type: 'boolean' },
        { name: 'prescriber_name', type: 'string', isOptional: true },
        { name: 'document_date', type: 'string', isOptional: true },
        { name: 'note', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'last_synced_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'audit_logs',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'action', type: 'string' },
        { name: 'entity_type', type: 'string' },
        { name: 'entity_id', type: 'string' },
        { name: 'context', type: 'string', isOptional: true },
        { name: 'synced', type: 'boolean', isIndexed: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'offline_queue',
      columns: [
        { name: 'op_type', type: 'string' },
        { name: 'payload', type: 'string' },
        { name: 'retry_count', type: 'number' },
        { name: 'max_retries', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'user_cache',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'email', type: 'string' },
        { name: 'first_name', type: 'string' },
        { name: 'last_name', type: 'string' },
        { name: 'rpps', type: 'string' },
        { name: 'cabinet_id', type: 'string' },
        { name: 'cabinet_name', type: 'string' },
      ],
    }),
  ],
});
